spring:
  config:
    activate:
      on-profile: develop
cloud:
  aws:
    cloudwatch:
      group-name: /aws/ec2/instance/hiel-side-develop/log
      stream-prefix: hiel-side-develop-
    s3:
      bucket: hiel-side-develop
allow-origin-urls: https://hiel-side-client-web-git-develop-hiel1s-projects.vercel.app
web-client-url: https://hiel-side-client-web-git-develop-hiel1s-projects.vercel.app
