spring:
  config:
    activate:
      on-profile: local
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: none
logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
cloud:
  aws:
    cloudwatch:
      group-name: /aws/ec2/instance/hiel-side-develop/log
      stream-prefix: hiel-side-develop-
    s3:
      bucket: hiel-side-develop
allow-origin-urls: http://localhost:3000
web-client-url: http://localhost:3000
