spring:
  datasource:
    url: jdbc:mysql://localhost:3306
    username: root
    password: hiel
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    username: hiel@hiel.com
    password: hiel
cloud:
  aws:
    credentials:
      access-key: hiel
      secret-key: hiel
jwt:
  secret-key: hiel
