### 내역 카테고리 등록
POST {{host}}/account-book/transaction-categories
Content-Type: application/json; charset=utf-8
Authorization: Bearer {{access-token}}

{
    "name": "식비"
}


### 내역 카테고리 수정
PUT {{host}}/account-book/transaction-categories/1
Content-Type: application/json; charset=utf-8
Authorization: Bearer {{access-token}}

{
    "name": "식비"
}


### 내역 카테고리 삭제
DELETE {{host}}/account-book/transaction-categories/1
Content-Type: application/json; charset=utf-8
Authorization: Bearer {{access-token}}


### 내역 카테고리 목록 조회
GET {{host}}/account-book/transaction-categories
Content-Type: application/json; charset=utf-8
Authorization: Bearer {{access-token}}
