### 내역 등록
POST {{host}}/account-book/transactions
Content-Type: application/json; charset=utf-8
Authorization: Bearer {{access-token}}

{
    "incomeExpenseType": "EXPENSE",
    "title": "맥도날드",
    "price": 10000,
    "isWaste": false,
    "assetCategoryId": 1,
    "transactionCategoryId": 1,
    "transactionDate": "2024-12-01T00:00:00.000+09:00"
}


### 내역 수정
PUT {{host}}/account-book/transactions/1
Content-Type: application/json; charset=utf-8
Authorization: Bearer {{access-token}}

{
    "incomeExpenseType": "EXPENSE",
    "title": "맥도날드",
    "price": 10000,
    "isWaste": false,
    "assetCategoryId": 1,
    "transactionCategoryId": 1,
    "transactionDate": "2024-12-01T00:00:00.000+09:00"
}


### 내역 삭제
DELETE {{host}}/account-book/transactions/1
Content-Type: application/json; charset=utf-8
Authorization: Bearer {{access-token}}


### 내역 상세 조회
GET {{host}}/account-book/transactions/1
Content-Type: application/json; charset=utf-8
Authorization: Bearer {{access-token}}


### 내역 목록 조회
GET {{host}}/account-book/transactions
    ?page=1
    &pageSize=20
#    &date=2024-12-01
Content-Type: application/json; charset=utf-8
Authorization: Bearer {{access-token}}
